
title: "Jean Kapsa"
tagline: ""
description: "Follow <a href=\"https://micro.blog/kapsa\">@kapsa on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/kapsa\">@kapsa on Micro.blog</a>."
baseurl: ""
url: "https://www.jeankapsa.com"
markdown: "kramdown"
username: "kapsa"
microblog_user: "kapsa"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Jean Kapsa"
name: "Jean Kapsa"
gravatar_hash: "fb4a7cb971644ec9228e9ced2b887096"
avatar: "https://micro.blog/kapsa/avatar.jpg"
full_name: "Jean Kapsa"
bio: ""
twitter_username: "jeankapsa"
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "Poland"
site_id: "1477"
gems: ["jekyll-paginate"]
itunes_category: "Music"
itunes_subcategory: ""
itunes_author: "Jean Kapsa"
podcast: false